/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example.app

import org.example.utilities.StringUtils

import org.apache.commons.text.WordUtils

class Coche(private var _marca: String = "Ford", private var _modelo: Int = 2020) {
    var marca: String
        get() = _marca
        set(value) {
            _marca = value
        }
    var modelo: Int
        get() = _modelo
        set(value) {
            _modelo = value
        }
}

fun main() {

    val coche = Coche("Chevrolet", 2025)

    println("Marca ${coche.marca}")
    println("Modelo ${coche.modelo}")

}